#!/bin/bash

SRC="$1"
CON="$2"
cur="nothing"

git stash > /dev/null
if [[ "$SRC" != "" ]]; then
  git checkout $SRC
fi

while true; do
  if [[ "$CON" == "$cur" ]]; then
    exit
  fi
  logfile="`mktemp`.build"
  git stash >> $logfile
  git checkout HEAD^1 >> $logfile
  make clean >> $logfile
  if $(make reload >> $logfile 2>&1 && make tests >> $logfile 2>&1); thenA
    echo `tput setaf 2`PASS`tput sgr0`:`git ll`
    cur="pass"
    continue
  fi
  echo `tput setaf 1`FAIL`tput sgr0`:`git ll`
  cur="fail"
done
