#!/bin/sh

patch_dir=$HOME/Dropbox/src/Patches/outgoing/net-next

mkdir -p $patch_dir
git format-patch --subject-prefix='PATCH net-next' HEAD^1 -o $patch_dir

echo "Remember to run (kernel/scripts/get_maintainer.pl) for recipients to your patch"
echo "Check your patch for obvious issues (kernel/scripts/checkpatch.pl), but you know that ;)"
