#!/bin/bash

#TODO: merge more of the scripts from cilium/ into this file

cmd="$1"

run_test() {
  test_file="$1"
  echo "# Will run test $test_file"
  sudo -E env PATH="${PATH}" ./$test_file
}

draft_weekly_notes() {
  git log --since="1 week" --author=Alemayhu --pretty=oneline --all
}

run_bisection () {
  checker="$@"
  echo "Starting bisection (assuming bad start)"
  echo "checks performed via '$checker'"
  while true; do
    if eval "$checker"; then
      echo `tput setaf 2`GOOD`tput sgr0`:`git ll`
      break
    else
      echo `tput setaf 1`BAD`tput sgr0`:`git ll`
    fi
    # Prevent rerunning initial commit
    if ! git checkout HEAD^1; then
      break
    fi
  done
}

if [[ "$1" == "run_test" ]]; then
  run_test "$2"
elif [[ "$1" == "run_runtime_tests" ]]; then
  sudo -E env PATH="${PATH}" make -C ${GOPATH}/src/github.com/cilium/cilium runtime-tests
elif [[ "$1" == "weekly_notes" ]]; then
  draft_weekly_notes
elif [[ "$1" == "bisect" ]]; then
  shift
  run_bisection "$@"
else
  echo "unsupported options '$@'"
  # TODO: print usage
fi
