#!/bin/sh

prefix="$@"
kernel_dir=$HOME/src/github.com/scanf/linux
patch_dir="$HOME/Dropbox/src/Patches/outgoing/$prefix"

mkdir -p $patch_dir

if [ -n "$1" ]; then
format_patch=`git format-patch --subject-prefix="PATCH $prefi" HEAD^1 -o $patch_dir`
else
format_patch=`git format-patch -M HEAD^1 -o $patch_dir`
fi


echo $format_patch

echo MAINTAINER INFO
$kernel_dir/scripts/get_maintainer.pl $format_patch
echo

echo CHECKPATCH
$kernel_dir/scripts/checkpatch.pl --terse $format_patch
