#!/bin/sh

prefix="$@"
kernel_dir=$HOME/src/github.com/scanf/linux
queue_dir="$HOME/src/github.com/scanf/queue/"
patch_dir="$queue_dir/$prefix"

if [ -d "$queue_dir" ]; then
  git clone https://github.com/scanf/queue $queue_dir
fi

mkdir -p $patch_dir

if [ -n "$1" ]; then
  format_patch=`git format-patch --subject-prefix="PATCH $prefix" HEAD^1 -o $patch_dir`
else
  format_patch=`git format-patch -M HEAD^1 -o $patch_dir`
fi

echo $format_patch

echo MAINTAINER INFO
$kernel_dir/scripts/get_maintainer.pl $format_patch
echo

echo CHECKPATCH
$kernel_dir/scripts/checkpatch.pl --terse $format_patch

echo GIT
git -C $patch_dir add .
git -C $patch_dir commit -s -m "`basename $format_patch`"
