#!/bin/bash

set -x
set -e

check_for()
{
  if [ ! -f $1 ]; then
    echo "fatal: did not detect $1"
    echo "Please run in the top level kernel directory!"
    exit
  fi
}

check_for Kconfig

if [[ "install" == $1 ]]; then
  echo skipping build
else
  make clean
  echo "INFO: expecting only one config file in /boot/"
  check_for .config
  make olddefconfig
  make -j`grep -Pc '^processor\t' /proc/cpuinfo`
  make modules
fi

if [[ "build" == $1 ]]; then
  echo skipping install
else
  sudo make modules_install
  sudo make install

  if [ -f /etc/fedora-release ]; then
    sudo grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
  else
    echo "sudo grub2-mkconfig  -o /boot/grub2/grub.cfg"
  fi
  echo "Maybe you also want to?\nsudo make headers_install INSTALL_HDR_PATH=/usr"
fi
