#!/bin/sh
make clean
make localmodconfig
make -j$1
make modules
sudo make modules_install
sudo make install
echo "Maybe you also want to?\nsudo make headers_install INSTALL_HDR_PATH=/usr"
echo "sudo grub2-mkconfig  -o /boot/grub2/grub.cfg"
echo "or sudo grub2-mkconfig  -o /boot/efi/EFI/fedora/grub.cfg"
