#!/bin/bash

export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
export DBLATEX=no
export DOCBOOK2X_MAN=no
export DOCBOOK2MAN=no
export DB2X_DOCBOOK2MAN=no

set -x
set -e

src=~/src/netfilter.org
mkdir -pv $src
cd $src

for project in libmnl libnftnl nftables
do
  if [ -d "$src/$project" ]; then
    git -C $project fetch --all
    git -C $project pull
    cd $project
    sh autogen.sh
    if [[ $project == "libnftnl" ]]
    then
      ./configure --with-json-parsing
    else
      ./configure
    fi
    make clean
    make
    sudo make install
    sudo ldconfig
    cd $src
  else
    git clone git://git.netfilter.org/$project
  fi
done
