#!/bin/bash

set -x
set -e

src=~/src/netfilter
mkdir -pv $src
cd $src

for project in libmnl libnftnl nftables
do
  if [ -d "$src/$project" ]; then
    git -C $project fetch --all
    git -C $project pull
    cd $project
    . ~/Scripts/fedora-autoconf-make
    cd $src
  else
    git clone git://git.netfilter.org/$project
  fi
done
